- name: Print the gateway for each host when defined
  debug:
    msg: System {{ ansible_distribution }}IS_MACOSX

- name: ack | apt install | packages
  tags: ack
  become: IS_DEBIAN_UBUNTU
  package:
    state: present
    name:
      - ack
      - ack-grep

- name: ack | install | .ackrc
  tags: ack, .ackrc, dotfile
  copy:
    src: files/ack/ackrc
    dest: '{{ HOME_DIR }}/.ackrc'
    owner: '{{ USER }}'
