- name: Print the gateway for each host when defined
  debug:
    msg: '{{ ansible_distribution }} ?? {{IS_MACOSX}}'

- name: Print IS_MACOSX
  debug:
    msg: '{{ IS_MACOSX }}'

- name: Print IS_UBUNTU
  debug:
    msg: '{{ IS_UBUNTU }}'

- name: ack | apt install | packages
  tags: ack
  become: no
  package:
    state: present
    name:
      - ack
      - ack-grep

- name: ack | install | .ackrc
  tags: ack, .ackrc, dotfile
  copy:
    src: files/ack/ackrc
    dest: '{{ HOME_DIR }}/.ackrc'
    owner: '{{ USER }}'
