- name: ack |apt install | packages
  tags: ack
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    state: present
    name:
      - ack
      - ack-grep

- name: ack | install | .ackrc
  tags: ack, .ackrc, dotfile
  copy:
    src: files/ack/ackrc
    dest: '{{ HOME_DIR }}/.ackrc'
    owner: '{{ USER }}'
