- name: git | install | packages
  tags: git
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    state: present
    name:
      - git
      - git-all
      - git-crypt

- name: git | install | .gitattributes
  tags: git, .gitattributes, dotfile
  copy:
    src: files/git/gitattributes
    dest: '{{ HOME_DIR }}/.gitattributes'
    owner: '{{ USER }}'

- name: git | install | .gitconfig
  tags: git, .gitconfig, dotfile
  copy:
    src: files/git/gitconfig
    dest: '{{ HOME_DIR }}/.gitconfig'
    owner: '{{ USER }}'

- name: git | install | .gitignore
  tags: git, .gitignore, dotfile
  copy:
    src: files/git/gitignore
    dest: '{{ HOME_DIR }}/.gitignore'
    owner: '{{ USER }}'

- name: git | hetwebbureau | project directory
  file:
    path: "{{ HETWEBBUREAU_DIR }}"
    state: directory

- name: Find pwd route
  shell: pwd
  register: playbook_path_output
- debug: var=playbook_path_output.stdout

- name: Find out tilde route
  shell: "cd ~"
  register: playbook_path_outputt
- debug: var=playbook_path_outputt.stdout

- name: repositories installer | clone
  become_user: USER
  tags: repository, clone
  git:
    repo: git@bitbucket.org:R4YM3/private-repositories-installer.git
    dest: '{{ HETWEBBUREAU_DIR }}/private-repositories-installer'
    clone: yes
    key_file: '{{ HOME_DIR }}/.ssh/id_rsa'

- name: repositories installer | clone
  become_user: USER
  tags: repository, clone
  command: "sh {{ HETWEBBUREAU_DIR }}/private-repositories-installer/install.sh {{DEVELOPMENT_DIR}}"
