- name: git | install | packages
  tags: git
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    state: present
    name:
      - git
      - git-all
      - git-crypt

- name: git | install | .gitattributes
  tags: git, .gitattributes, dotfile
  copy:
    src: files/git/gitattributes
    dest: '{{ HOME_DIR }}/.gitattributes'
    owner: '{{ USER }}'

- name: git | install | .gitconfig
  tags: git, .gitconfig, dotfile
  copy:
    src: files/git/gitconfig
    dest: '{{ HOME_DIR }}/.gitconfig'
    owner: '{{ USER }}'

- name: git | install | .gitignore
  tags: git, .gitignore, dotfile
  copy:
    src: files/git/gitignore
    dest: '{{ HOME_DIR }}/.gitignore'
    owner: '{{ USER }}'
