- name: tmux | install
  tags: tmux
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    state: present
    name:
      - tmux

- name: tmux | install | .tmux.conf
  tags: tmux, .tmux.conf, dotfile
  copy:
    src: tmux/tmux.conf
    dest: '{{ CONFIG_DIR }}/.tmux.conf'
    owner: '{{ USER }}'
