- name: vim | install
  tags: vim
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    state: present
    name:
      - vim
      - neovim

- name: create nvim directory
  file:
    path: '{{NVIM_DIR}}'
    state: directory
    owner: '{{ USER }}'

- name: vim | install | .vimrc
  tags: vim, dotfile
  copy:
    src: vim/vimrc
    dest: '{{ NVIM_DIR }}/init.vim'
    owner: '{{ USER }}'

- name: vim | install | .ctags
  tags: vim, dotfile, ctags
  copy:
    src: vim/ctags
    dest: '{{ HOME_DIR }}/.ctags'
    owner: '{{ USER }}'

- name: vim | :PlugInstall
  tags: vim, plugins, install
  shell: "vim +'PlugInstall --sync' +qall &> /dev/null"

- name: vim | YCM dependecies 
  tags: vim, ycm
  become: yes
  package:
    state: present
    name:
      - python3-dev
      - cmake

- name: zsh | start YCM server
  tags: vim, ycm
  become: yes
  user:
    name: '{{ USER }}'
    shell: "python3 {{ HOME_DIR }}/.config/nvim/plugged/youcompleteme/install.py --ts-completer"

- name: vim | install | aliases
  tags: vim, aliases
  copy:
    src: files/vim/aliases
    dest: '{{ ALIASES_DIR }}/vim'
    owner: '{{ USER }}'
