- name: zsh | apt | install zsh and dependecies
  tags: zsh
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    name:
      - git
      - zsh
    state: latest

- name: zsh | MacOS | set as default
  tags: zsh
  become: yes
  user:
    name: '{{ USER }}'
    shell: "chsh -s /usr/local/bin/zsh"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: zsh | not MacOS | set as default
  tags: zsh
  become: yes
  user:
    name: '{{ USER }}'
    shell: /bin/zsh
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: zsh | check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result

- name: zsh | check if .oh-my-zsh exists
  stat:
    path: '{{ OHMYZSH_DIR }}'
  register: stat_oh_my_zsh_result

- name: zsh | clone oh-my-zsh
  tags: zsh, oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: '{{ OHMYZSH_DIR }}'
    clone: yes
  when: not stat_oh_my_zsh_result.stat.exists

- name: zsh | oh-my-zsh | clone zsh-nvm
  tags: zsh, oh-my-zsh
  git:
    repo: https://github.com/lukechilds/zsh-nvm.git
    dest: '{{ OHMYZSH_PLUGINS_DIR }}/zsh-nvm'
    clone: yes
  when: not stat_oh_my_zsh_result.stat.exists

- name: zsh | oh-my-zsh | clone zsh-autosuggestions
  tags: zsh, oh-my-zsh
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: '{{ OHMYZSH_PLUGINS_DIR }}/zsh-autosuggestions'
    clone: yes
  when: not stat_oh_my_zsh_result.stat.exists

- name: zsh | oh-my-zsh | clone zsh-autosuggestions
  tags: zsh, oh-my-zsh
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: '{{ OHMYZSH_PLUGINS_DIR }}/zsh-syntax-highlighting'
    clone: yes
  when: not stat_oh_my_zsh_result.stat.exists

- name: zsh | copy zshrc
  tags: zsh
  copy:
    src: zsh/zshrc
    dest: '{{ HOME_DIR }}/.zshrc'
    owner: '{{ USER }}'

- name: zsh | copy config
  tags: zsh
  copy:
    src: zsh/config
    dest: "{{ ZSH_DIR }}"
    owner: '{{ USER }}'
    mode: u+x
