- name: zsh | apt | install zsh and dependecies
  tags: zsh
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    name:
      - git
      - zsh
    state: latest

- name: zsh | MacOS | set as default
  tags: zsh
  become: yes
  user:
    name: '{{ USER }}'
    shell: "chsh -s /usr/local/bin/zsh"
  when : "{{ ansible_distribution == 'MacOSX' }}"

- name: zsh | not MacOS | set as default
  tags: zsh
  become: yes
  user:
    name: '{{ USER }}'
    shell: /bin/zsh
  when : "{{ ansible_distribution != 'MacOSX' }}"

- name: zsh | check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result

- name: zsh | check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: zsh | cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

- name: zsh | copy zshrc
  tags: zsh
  copy:
    src: zsh/zshrc
    dest: '{{ HOME_DIR }}/.zshrc'
    owner: '{{ USER }}'

- name: zsh | copy config
  tags: zsh
  copy:
    src: "{{ item }}"
    dest: "{{ ZSH_DIR }}"
    owner: '{{ USER }}'
  with_fileglob:
    - zsh/config/*
