# https://github.com/gantsign/ansible-role-oh-my-zsh/blob/master/tasks/install.yml
---
- name: zsh | apt | install zsh and dependecies
  tags: zsh
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    name:
      - git
      - zsh
    state: latest

- name: zsh | MacOS | set as default
  tags: zsh
  become: yes
  user:
    name: '{{ USER }}'
    shell: "chsh -s /usr/local/bin/zsh"
  when : "{{ ansible_distribution == 'MacOSX' }}"

- name: zsh | not MacOS | set as default
  tags: zsh
  become: yes
  user:
    name: '{{ USER }}'
    shell: /bin/zsh
  when : "{{ ansible_distribution != 'MacOSX' }}"

- name: zsh | check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result

- name: zsh | check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: zsh | cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

#- name: Creating new ~/.zshrc
#  copy:
#    src=~/.oh-my-zsh/templates/zshrc.zsh-template
#    dest=~/.zshrc
#  when: not stat_rc_result.stat.exists

- name: zsh | dotfiles
  tags: zsh
  copy: src={{ item.src }} dest={{ item.dest }}
  owner: '{{ USER }}'
  with_items:
    - { src: 'files/zsh/zshrc', dest: '{{ CONFIG_DIR }}/.zshrc' }
    - { src: 'files/zsh/aliases', dest: '{{ ZSH_DIR }}/.aliases' }
    - { src: 'files/zsh/exports', dest: '{{ ZSH_DIR }}/.exports' }
    - { src: 'files/zsh/functions', dest: '{{ ZSH_DIR }}/.functions' }
    - { src: 'files/zsh/plugins', dest: '{{ ZSH_DIR }}/.plugins' }
    - { src: 'files/zsh/preferences', dest: '{{ ZSH_DIR }}/.preferences' }
  when: not stat_rc_result.stat.exists
