---
- hosts: localhost
  connection: local
  tasks:

  - name: install apt packages
    become: yes
    package:
      name:
        - ack-grep
        - awscli
        - catimg
        - curl
        - cmake
        - fonts-firacode
        - fonts-powerline
        - git
        - git-all
        - git-crypt
        - htop
        - lynx
        - make
        - neovim
        - nodejs
        - openconnect
        - powerline
        - python3
        - snapd
        - tmux
        - tmuxinator
        - zsh
      state: present

  - name: install snap packages
    become: yes
    package:
      name:
        - beekeeper-studio
        - chromium
        - code --classic
        - discord
        - gitkraken --classic
        - icloud-for-linux
        - libreoffice
        - mailspring
        - opera
        - postman
        - slack --classic
        - teams-for-linux
        - vlc
      state: present
