---
- hosts: localhost
  tags: always


- name: Include only files matching bastion.yaml (2.2)
  include_vars:
    dir: vars
    files_matching: "{{ ansible_distribution }}.yml"

- hosts: all
  tags: base
  roles:
    - base
