---
- hosts: localhost
  connection: local
  tasks:

  - name: install apt packages
    become: yes
    package:
      state: present
      name:
        - ack-grep
        - awscli
        - catimg
        - curl
        - cmake
        - fonts-firacode
        - fonts-powerline
        - git
        - git-all
        - git-crypt
        - htop
        - lynx
        - make
        - neovim
        - nodejs
        - npm
        - openconnect
        - powerline
        - python3
        - snapd
        - tmux
        - tmuxinator
        - zsh

  # - name: install snap packages
  #  become: yes
  #  snap:
  #    state: present
  #    name:
  #      - discord
  #      - libreoffice
  #      - mailspring
  #      - opera
  #      - postman
  #      - slack
  #      - teams-for-linux
  #      - vlc

  - name: install classic snap packages
    become: yes
    snap:
      classic: yes
      state: present
      name:
        - beekeeper-studio
        # - code
        - chromium
        - gitkraken
        - icloud-for-linux


  - name: install eslint
    npm:
      state: present
      global: yes
      name: eslint

  - name: install grunt
    npm:
      state: present
      global: yes
      name: eslint

  - name: install gulp
    npm:
      state: present
      global: yes
      name: eslint

  - name: install gtop
    npm:
      state: present
      global: yes
      name: eslint

  - name: install http-server
    npm:
      state: present
      global: yes
      name: eslint

  - name: install nodemon
    npm:
      state: present
      global: yes
      name: eslint
