---
- hosts: localhost
  connection: local
  tasks:

  - name: install apt packages
    become: yes
    package:
      state: present
      name:
        - ack-grep
        - awscli
        - catimg
        - curl
        - cmake
        - fonts-firacode
        - fonts-powerline
        - git
        - git-all
        - git-crypt
        - htop
        - lynx
        - make
        - neovim
        - nodejs
        - openconnect
        - powerline
        - python3
        - snapd
        - tmux
        - tmuxinator
        - zsh

  - name: install snap packages
    become: yes
    snap:
      classic: yes
      state: present
      name:
        - beekeeper-studio
        - chromium
        # - code
        # - discord
        - gitkraken
        - icloud-for-linux
        - libreoffice
        - mailspring
        - opera
        - postman
        - slack
        - teams-for-linux
        - vlc

  - name: instal global npm packages
    npm:
      state: present
      name:
        - eslint
        - grunt
        - gulp
        - gtop
        - http-server
        - nodemon

