- name: directories | create config directory
  file:
    path: '{{ CONFIG_DIR }}'
    state: directory
    owner: '{{ USER }}'
    mode: 0755

- name: directories | create aliases directory
  file:
    path: '{{ALIASES_DIR}}'
    state: directory
    owner: '{{ USER }}'
    mode: 0755
