- name: git | apt install | packages
  tags: git, apt
  become: yes
  package:
    state: present
    name:
      - git
      - git-all
      - git-crypt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: git | homwbrew install | packages
  tags: git, homebrew
  become: no
  homebrew:
    state: present
    name:
      - git
      - git-all
      - git-crypt
  when: ansible_distribution == 'MacOSX'

- name: git | install | .gitattributes
  tags: git, .gitattributes, dotfile
  copy:
    src: files/git/gitattributes
    dest: '{{ CONFIG_DIR }}/.gitattributes'
    owner: '{{ USER }}'

- name: git | install | .gitconfig
  tags: git, .gitconfig, dotfile
  copy:
    src: files/git/gitconfig
    dest: '{{ CONFIG_DIR }}/.gitconfig'
    owner: '{{ USER }}'

- name: git | install | .gitignore
  tags: git, .gitignore, dotfile
  copy:
    src: files/git/gitignore
    dest: '{{ CONFIG_DIR }}/.gitignore'
    owner: '{{ USER }}'
