- name: homebrew | install | packages
  tags: packages, homebrew
  become: no
  homebrew:
    state: present
    name:
      - docker
      - docker-compose
      - ffmpeg
      - mono
      - ncdu
      - wget
