- name: apt | install | packages
  tags: packages, apt
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    state: present
    name:
      - awscli
      - catimg
      - cmake
      - fonts-powerline
      - htop
      - lynx
      - lolcat
      - make
      - npm
      - openconnect
      - powerline
      - python3
      - zsh


