- name: apt | install | packages
  tags: packages, apt
  become: yes
  package:
    state: present
    name:
      - ack-grep
      - awscli
      - catimg
      - curl
      - cmake
      - fonts-firacode
      - fonts-powerline
      - git
      - git-all
      - git-crypt
      - htop
      - lynx
      - make
      - nodejs
      - npm
      - openconnect
      - powerline
      - python3
      - snapd
      - zsh
