- name: snap | install | classic packages
  tags: packages, snap
  become: yes
  snap:
    classic: yes
    state: present
    name:
      # - code
      - gitkraken
      - opera

- name: snap | install | classic packages
  tags: packages, snap
  become: yes
  snap:
    state: present
    name:
      - beekeeper-studio
      - chromium
      # - discord
      - icloud-for-linux
      # - libreoffice
      # - mailspring

      - postman
      - slack
      - teams-for-linux
      # - vlc
