# - name: install snap packages
#  become: yes
#  snap:
#    state: present
#    name:
##     - code
#      - discord
#      - libreoffice
#      - mailspring
#      - opera
#      - slack
#      - vlc

- name: snap | install | classic packages
  tags: packages, snap
  become: yes
  snap:
    classic: yes
    state: present
    name:
      - beekeeper-studio
      - chromium
      - gitkraken
      - icloud-for-linux

- name: snap | install | classic packages
  tags: packages, snap
  become: yes
  snap:
    classic: yes
    state: present
    name:
      - 1password
      - slack
      - teams-for-linux
      - postman
      - robo3t-snap
  when: ansible_distribution_version == '21.04'
