# - name: install snap packages
#  become: yes
#  snap:
#    state: present
#    name:
#      - discord
#      - libreoffice
#      - mailspring
#      - opera
#      - postman
#      - slack
#      - teams-for-linux
#      - vlc

- name: snap | install | classic packages
  tags: packages, snap
  become: yes
  snap:
    classic: yes
    state: present
    name:
      - 1password
      - beekeeper-studio
      # - code
      - chromium
      - gitkraken
      - icloud-for-linux
      - slack
      - teams-for-linux
      - opera
      - postman
      - robo3t-snap
