- name: snap | install | classic packages
  tags: packages, snap
  become: yes
  snap:
    classic: yes
    state: present
    name:
      # - code
      - gitkraken
      - slack

- name: snap | install | classic packages
  tags: packages, snap
  become: yes
  snap:
    state: present
    name:
      - 1password
      - beekeeper-studio
      - chromium
      - discord
      - icloud-for-linux
      - libreoffice
#      - mailspring
      - opera
      - postman
      - teams-for-linux
      - vlc
