- name: terminal | theme | clone dracula theme
  tags: terminal, theme, dracula
  git:
    repo: https://github.com/dracula/gnome-terminal.git
    dest: '{{ TERMINAL_THEMES_DIR }}/dracula'
    clone: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: terminal | make new default profile
  shell: >
    profile_id="$(uuidgen)"
    dconf write $dconfdir/default "'$profile_id'"
    dconf write $dconfdir/list "['$profile_id']"
    profile_dir="$dconfdir/:$profile_id"
    dconf write $profile_dir/visible-name "'Default'"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# https://github.com/dracula/gnome-terminal/issues/11
- name: terminal | install dracula theme
  shell: >
    'cd {{ TERMINAL_THEMES_DIR }}/dracula
    && ./install.sh -s Dracula -p Default --install-dircolors'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Terminal hide menubar
  dconf:
    key: '/org/gnome/terminal/legacy/default-show-menubar'
    value: 'false'

- name: Terminal hide scrollbar
  dconf:
    key: '/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/scrollbar-policy'
    value: "'never'"

- name: Set terminal font to firacode
  dconf:
    key: '/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font'
    value: "'Fira Code weight=453 12'"

- name: Set terminal font to firacode
  dconf:
    key: '/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font'
    value: 'false'
