- name: macos | quicklook | plugins
  tags: macos, quicklook
  homebrew:
    state: present
    name:
      - apparency
      - qlcolorcode
      - qlmarkdown
      - qlprettypatch
      - qlstephen
      - qlvideo
      - quicklook-csv
      - quicklook-json
      - quicklookase
      - suspicious-package
      - webpquicklook
