- name: macos | quicklook | plugins
  tags: macos, quicklook
  homebrew:
    state: present
    name:
      - apparency
      - qlcolorcode
      - qlmarkdown
      - qlprettypatch
      - qlstephen
      - qlvideo
      - quicklook-csv
      - quicklook-json
      - quicklookase
      - suspicious-package
      - webpquicklook

- name: macos | quicklook | plugin permissions
  tags: macos, quicklook
  become_user: USER
  shell: 'xattr -cr ~/Library/QuickLook/*.qlgenerator'
