- include_vars: "{{ ansible_distribution }}.yml"
  tags: always


- debug: msg="{{ lookup('env','HOME') }}"

- debug: msg="{{ ansible_user_dir }}"

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4

- name: create config directory
  file:
    path: '{{ansible_user_dir}}/.config'
    state: directory
    mode: 0755

- name: create aliases directory
  file:
    path: '{{ansible_user_dir}}/.config/aliases'
    state: directory
    mode: 0755

- name: create nvim directory
  file:
    path: '{{ansible_user_dir}}/.config/nvim'
    state: directory
    mode: 0755

# software
- block:
  - import_tasks: software/packages_apt.yml
  - import_tasks: software/packages_snap.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- block:
  - import_tasks: software/packages_homebrew.yml
  - import_tasks: software/packages_homebrew_cask.yml
  when: ansible_distribution == 'MacOSX'

- import_tasks: software/vim.yml
- import_tasks: software/tmux.yml
- import_tasks: software/tmuxinator.yml

- import_tasks: software/packages_npm.yml

# desktop enviroments
- import_tasks: desktop_environments/macos/quicklook.yml
  when: ansible_distribution == 'MacOSX'
