- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

# software
- block:
  - import_tasks: software/packages_apt.yml
  - import_tasks: software/packages_snap.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- block:
  - import_tasks: software/packages_homebrew.yml
  - import_tasks: software/packages_homebrew_cask.yml
  when: ansible_distribution == 'MacOSX'

- import_tasks: software/vim.yml
- import_tasks: software/tmux.yml

- import_tasks: software/packages_npm.yml

# desktop enviroments
- import_tasks: desktop_environments/macos/quicklook.yml
  when: ansible_distribution == 'MacOSX'
