- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: create config directory
  file:
    path: '{{ CONFIG_DIR }}'
    state: directory
    owner: '{{ USER }}'
    mode: 0755

- name: create aliases directory
  file:
    path: '{{ALIASES_DIR}}'
    state: directory
    owner: '{{ USER }}'
    mode: 0755

# utilities
- import_tasks: utilities/curl.yml
- import_tasks: utilities/git.yml
- import_tasks: utilities/ack.yml
- import_tasks: utilities/vim.yml
- import_tasks: utilities/tmux.yml
- import_tasks: utilities/tmuxinator.yml
- import_tasks: utilities/packages_npm.yml

# software
- block:
  - import_tasks: software/packages_apt.yml
  - import_tasks: software/packages_snap.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- block:
  - import_tasks: software/packages_homebrew.yml
  - import_tasks: software/packages_homebrew_cask.yml
  when: ansible_distribution == 'MacOSX'

# desktop enviroments
- import_tasks: desktop_environments/macos/quicklook.yml
  when: ansible_distribution == 'MacOSX'
