- import_tasks: software/packages_apt.yml
- import_tasks: software/packages_snap.yml

- import_tasks: software/packages_homebrew.yml
- import_tasks: software/packages_homebrew_cask.yml

- import_tasks: software/packages_npm.yml
