- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- import_tasks: desktop_environments/directories.yml

- name: Distribution version
  debug: msg="{{ ansible_distribution_version}}"

- import_tasks: utilities/ack.yml
- import_tasks: utilities/curl.yml
- import_tasks: utilities/git.yml
- import_tasks: utilities/zsh.yml
- import_tasks: utilities/tmux.yml
- import_tasks: utilities/tmuxinator.yml
- import_tasks: utilities/vim.yml
- import_tasks: utilities/wget.yml

- import_tasks: software/packages.yml

- block:
  - import_tasks: software/apt.yml
  - import_tasks: software/snap.yml
    # - import_tasks: software/google-chrome.yml
  when: IS_DEBIAN_UBUNTU

- block:
  - import_tasks: software/homebrew.yml
  - import_tasks: software/homebrew_cask.yml
  when: IS_MACOSX

- block:
  - import_tasks: desktop_environments/gnome/appearance.yml
  - import_tasks: desktop_environments/gnome/cursor.yml
  - import_tasks: desktop_environments/gnome/keyboard.yml
  - import_tasks: desktop_environments/gnome/nautilus.yml
  - import_tasks: desktop_environments/gnome/night-light.yml
  - import_tasks: desktop_environments/gnome/packages.yml
  - import_tasks: desktop_environments/gnome/power.yml
  - import_tasks: desktop_environments/gnome/screen.yml
  - import_tasks: desktop_environments/gnome/terminal.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- block:
  - import_tasks: desktop_environments/macos/quicklook.yml
  when: IS_MACOSX
