- name: install apt packages
  become: yes
  package:
    state: present
    name:
      - ack-grep
      - awscli
      - catimg
      - curl
      - cmake
      - fonts-firacode
      - fonts-powerline
      - git
      - git-all
      - git-crypt
      - htop
      - lynx
      - make
      - neovim
      - nodejs
      - npm
      - openconnect
      - powerline
      - python3
      - snapd
      - tmux
      - tmuxinator
      - zsh
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# - name: install snap packages
#  become: yes
#  snap:
#    state: present
#    name:
#      - discord
#      - libreoffice
#      - mailspring
#      - opera
#      - postman
#      - slack
#      - teams-for-linux
#      - vlc

- name: install classic snap packages
  become: yes
  snap:
    classic: yes
    state: present
    name:
      - beekeeper-studio
      # - code
      - chromium
      - gitkraken
      - icloud-for-linux
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: software/packages_npm.yml
