- include_vars: "{{ ansible_distribution }}.yml"
  include_vars: "base.yml"
  tags: always

- name: Register current user name via whoami
  become: false
  local_action: command whoami
  register: whoami
  tags:
  - global
  - user

- name: Setting host facts using complex arguments
  set_fact:
    USER: '{{ whoami.stdout }}'
    HOME_DIR: '/home/{{ whoami.stdout }}'

- name: create config directory
  file:
    path: '{{ CONFIG_DIR }}'
    state: directory
    owner: '{{ USER }}'
    mode: 0755

- name: create aliases directory
  file:
    path: '{{ALIASES_DIR}}'
    state: directory
    owner: '{{ USER }}'
    mode: 0755

# utilities
- import_tasks: utilities/curl.yml
- import_tasks: utilities/git.yml
- import_tasks: utilities/ack.yml
- import_tasks: utilities/vim.yml
- import_tasks: utilities/tmux.yml
- import_tasks: utilities/tmuxinator.yml
- import_tasks: utilities/packages_npm.yml
- import_tasks: utilities/zsh.yml

# projects
# - import_tasks: projects/hetwebbureau.yml

# software
- block:
  - import_tasks: software/packages_apt.yml
  - import_tasks: software/packages_snap.yml
  - import_tasks: software/terminal.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- block:
  - import_tasks: software/packages_homebrew.yml
  - import_tasks: software/packages_homebrew_cask.yml
  when: ansible_distribution == 'MacOSX'

# desktop enviroments
- block:
  - import_tasks: desktop_environments/gnome/appearance.yml
  - import_tasks: desktop_environments/gnome/keyboard.yml
  - import_tasks: desktop_environments/gnome/cursor.yml
  - import_tasks: desktop_environments/gnome/power.yml
  - import_tasks: desktop_environments/gnome/night-light.yml
  - import_tasks: desktop_environments/gnome/screen.yml
  - import_tasks: desktop_environments/gnome/tracker.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- block:
  - import_tasks: desktop_environments/macos/quicklook.yml
  when: ansible_distribution == 'MacOSX'
