# Note: Some of these packages are disabled, they depend on tracker which is currently being disabled
- name: gnome | packages | install gnome packages
  tags: gnome,gnome-packages
  become: yes
  package:
    name:
      - eog
      - file-roller
      - gedit
      - gnome-backgrounds
      - gnome-control-center
      - gnome-disk-utility
      - gnome-icon-theme
      - gnome-shell
      - gnome-shell-extensions
      - gnome-system-monitor
      - gnome-terminal
      - gnome-todo
      - gnome-tweaks
      - nautilus

- name: gnome | packages | install flatpak support in gnome software
  tags: gnome,gnome-packages
  package:
    name:
    - gnome-software-plugin-flatpak
  when: ansible_distribution in ["Debian", "Ubuntu"]

# It appears as though Debian and Ubuntu place GNOME support for openvpn in a separate package
# This doesn't seem to be required in archlinux.
- name: gnome | packages | install gnome support for network-manager for debian and ubuntu hosts
  tags: gnome,gnome-packages,packages
  package:
    name:
      - network-manager-openvpn-gnome
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
